<?php

/* filename = 'language.extension' */

$lang_files=array();
$lang_files[]='english.utf8';
$lang_files[]='german.utf8';
$lang_files[]='danish.utf8';
$lang_files[]='portuguese.utf8';
$lang_files[]='turkish.utf8';

$lang_help=array();
$lang_help[]='english_help.utf8';
$lang_help[]='english_help.utf8';
$lang_help[]='danish_help.utf8';
$lang_help[]='english_help.utf8';
$lang_help[]='english_help.utf8';

/* --- */

$lang_admin=array();
$lang_admin[]='english_admin.utf8';


?>